INSERT INTO ETAPE(ETP_LIBELLE) VALUES('verification')
INSERT INTO ETAPE( ETP_LIBELLE) VALUES('objectif thérapeutique');
INSERT INTO ETAPE( ETP_LIBELLE) VALUES('observance');
INSERT INTO ETAPE( ETP_LIBELLE) VALUES('mesure de l''efficacité');

INSERT INTO DERNIERE_VALIDATION (ETP_NUM_DV, MED_DEPOTLEGAL_DV) VALUES (1, 'ADIMOL9');

INSERT INTO ETAPE_NORME(ETP_NUM_NORME, ETP_DATE_NORME, ETP_NORME) VALUES (1, GETDATE(), 'BON')