-- Script de création de la base de données GSB
-- Création de la base de données

USE GSB_gesAMM;

CREATE TABLE FAMILLE(
    FAM_CODE VARCHAR(3) NOT NULL PRIMARY KEY,
    FAM_LIBELLE VARCHAR(80) NOT NULL,
    FAM_NB_MED_AMM INT 
);

CREATE TABLE DECISION (
    DCS_ID INT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
    DCS_LIBELLE VARCHAR(15) NOT NULL
);

CREATE TABLE ETAPE (
    ETP_NUM INT  IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ETP_LIBELLE VARCHAR(50) NOT NULL,
);

CREATE TABLE ETAPE_NORME (
    ETP_NUM_NORME INT NOT NULL PRIMARY KEY,
    ETP_DATE_NORME DATE NOT NULL,
    ETP_NORME VARCHAR(50) NOT NULL,
    CONSTRAINT FK1 FOREIGN KEY (ETP_NUM_NORME)  REFERENCES ETAPE(ETP_NUM)
);

CREATE TABLE MEDICAMENT (
    MED_DEPOTLEGAL VARCHAR(10) NOT NULL PRIMARY KEY,
    MED_NOMCOMMERCIAL VARCHAR(25) NOT NULL,
    MED_COMPOSITION VARCHAR(255) NOT NULL,
    MED_EFFETS VARCHAR(255) NOT NULL,
    MED_CONTREINDIC VARCHAR(255) NOT NULL,
    MED_AMM VARCHAR(10) NULL,
    FAM_CODE_MEDICAMENT VARCHAR(3) NOT NULL,
    CONSTRAINT FK2 FOREIGN KEY (FAM_CODE_MEDICAMENT) REFERENCES FAMILLE(FAM_CODE)
);

CREATE TABLE SUBIR (
    ETP_NUM_SUBIR INT NOT NULL ,
    DATE_DECISION DATE NOT NULL,
    MED_DEPOTLEGAL_SUBIR VARCHAR(10) NOT NULL,
    DCS_ID_SUBIR INT NOT NULL,
    CONSTRAINT PK3 PRIMARY KEY  (ETP_NUM_SUBIR, MED_DEPOTLEGAL_SUBIR),
    CONSTRAINT FK4 FOREIGN KEY  (ETP_NUM_SUBIR) REFERENCES ETAPE(ETP_NUM),
    CONSTRAINT FK5 FOREIGN KEY  (MED_DEPOTLEGAL_SUBIR) REFERENCES MEDICAMENT(MED_DEPOTLEGAL),
    CONSTRAINT FK6 FOREIGN KEY  (DCS_ID_SUBIR) REFERENCES DECISION(DCS_ID)
);

CREATE TABLE DERNIERE_VALIDATION (
    ETP_NUM_DV INT NOT NULL,
    MED_DEPOTLEGAL_DV VARCHAR(10) NOT NULL,
    CONSTRAINT PK7 PRIMARY KEY (ETP_NUM_DV, MED_DEPOTLEGAL_DV),
    CONSTRAINT FK8 FOREIGN KEY (MED_DEPOTLEGAL_DV) REFERENCES MEDICAMENT(MED_DEPOTLEGAL),
    CONSTRAINT FK9 FOREIGN KEY (ETP_NUM_DV) REFERENCES ETAPE(ETP_NUM)
);

CREATE TABLE UTILISATEUR (
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
NOM VARCHAR(50) NOT NULL,
PRENOM VARCHAR(50) NOT NULL,
CODE_POSTALE VARCHAR(10) NOT NULL,
ADRESSE VARCHAR(150) NOT NULL,
VILLE VARCHAR(150) NOT NULL,
MAIL VARCHAR(100) NOT NULL,
MOT_DE_PASSE TEXT NOT NULL
);


CREATE TABLE HISTORIQUE (
ID_UTILISATEUR_HIST INT NOT NULL,
ETP_NUM_HIST INT NOT NULL,
DATE_MISE_A_JOUR DATE NOT NULL,
CONSTRAINT PK10 PRIMARY KEY (ID_UTILISATEUR_HIST,ETP_NUM_HIST,DATE_MISE_A_JOUR),
CONSTRAINT FK11 FOREIGN KEY (ID_UTILISATEUR_HIST) REFERENCES UTILISATEUR(ID),
CONSTRAINT FK12 FOREIGN KEY (ETP_NUM_HIST) REFERENCES ETAPE_NORME(ETP_NUM_NORME)
);